### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by quinnypig** [kylerankin/incident-response#1]
Is this envisioned as a user workstation compromise document, or should site compromises be in-scope?

**Comment by kylerankin** [comment]
Good question. I'd like to keep site compromise in scope as long as we can keep the doc simple, as most places don't have multiple IR docs around. I sort of see this document as having two halves: there's the top half for the first-responder on site who detects the problem, then the second half of the document that's for the incident response team. The top of the doc in that case could stay simple and more generalized, and could be where the first responders stop reading. Then the second half that's aimed at the response team could be fleshed out with more detail.

**Comment by quinnypig** [comment]
Doesn't this start to look like one of the Open Guides if it gets far enough? Food for thought...

**Comment by kylerankin** [comment]
If it gets too unwieldy (after all, I have a whole chapter just on incident response in my new book), we'll have to cut it down or move some of it to a different doc. The goal here should remain a basic boilerplate for small orgs/startups to use. Larger orgs probably already have an IR doc or a team that knows how to make one.
